spring:
  profiles:
    include: secret
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enable: true



server:
  error:
    include-exception: true
    include-stacktrace: always

