spring:
  main:
    allow-bean-definition-overriding: true
  profiles:

    default: local
    group:
      "local": local, secret
      "prod": prod, secret

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enable: true

logging:
  config: classpath:logback-spring.xml

server:
  error:
    include-exception: true
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    org:
      hibernate:
        SQL: info
#        SQL: debug
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  main:
    allow-bean-definition-overriding: true