spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enable: true

logging:
  config: classpath:logback-spring.xml

server:
  error:
    include-exception: true
    include-stacktrace: always

---

spring:
  profiles:
    default: local
    include: secret, console-logging, file-logging
logging:
  level:
    root: debug
---
spring:
  profiles:
    default: prod
    include: file-logging
logging:
  level:
    root: info
